# SPDX-FileCopyrightText: Copyright (c) 2020-2025 Objectionary
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
docker:
  image: yegor256/java
install: |
  sudo /usr/bin/install-node.sh
  sudo npm install -g eolang
merge:
  script: |
    make
